import type { Metadata } from "next";
import { Raleway } from "next/font/google";

import Header from "@/components/header";
import Footer from "@/components/footer";

const raleway = Raleway({
  subsets: ["latin", "cyrillic", "cyrillic-ext", "vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <Header />

      {children}
      <Footer />
    </main>
  );
}
